name: Foundry Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge Tests
        run: forge test -vvv
